import { ACCEPTED_LEGACY_DATABASE_SHA256, ACCEPTED_LEGACY_DATABASE_SIZE_BYTES } from "../storage/migration-plan.ts";
import type { Phase2CbMappingCandidate } from "./phase2cb-contracts.ts";

export function phase2CbB1aCandidate(): Phase2CbMappingCandidate {
  return {
    source: {
      databaseSha256: ACCEPTED_LEGACY_DATABASE_SHA256,
      sizeBytes: ACCEPTED_LEGACY_DATABASE_SIZE_BYTES,
      sqliteHeaderValid: true,
      quickCheck: "ok",
      integrityCheck: "ok",
      workspace: "synthetic",
      thoughtCount: 3,
      nodeCount: 3,
      linkCount: 1,
      embeddingCount: 3,
      unresolvedThoughtCount: 1,
      damagedReferenceCount: 1,
      eventCount: 5,
      runCount: 2,
      personalThoughtCount: 0,
    },
    target: {
      databaseName: "mindmap-state-core-v1-phase2cb-b1-fixture-placeholder",
      workspace: "synthetic",
      mode: "isolated-temporary",
      isEmpty: true,
      isTargetMacProduction: false,
    },
    nodes: [
      { id: "project-1", name: "Release proof", kind: "project", parentId: "direction-1", createdAt: "2026-07-25T00:02:00.000Z", status: "active", legacyMetadata: { source: "ai", confidence: 0.8 } },
      { id: "area-1", name: "Systems", kind: "area", createdAt: "2026-07-25T00:00:00.000Z", status: "active" },
      { id: "direction-1", name: "MindMap core", kind: "direction", parentId: "area-1", createdAt: "2026-07-25T00:01:00.000Z", status: "active" },
    ],
    thoughts: [
      {
        id: "synthetic-003",
        originalContent: "Preserve a broken legacy pointer explicitly",
        type: "Наблюдение",
        status: "inbox",
        createdAt: "2026-07-25T00:05:00.000Z",
        embeddingModel: "embeddinggemma",
        embedding: [0.5, -0.25],
        unresolved: { reason: "legacy_reference_damaged" },
        legacyMetadata: { title: "Broken pointer", tags: ["fixture"] },
        damagedReferences: [{
          field: "primaryNodeId",
          targetKind: "node",
          targetId: "missing-node",
          reason: "missing_target",
          detectedAt: "2026-07-25T00:05:01.000Z",
        }],
      },
      {
        id: "synthetic-001",
        originalContent: "Freeze the deterministic mapping contract",
        type: "Решение",
        status: "active",
        createdAt: "2026-07-25T00:03:00.000Z",
        embeddingModel: "embeddinggemma",
        embedding: [0.125, 0.25],
        primaryNodeId: "direction-1",
      },
      {
        id: "synthetic-002",
        originalContent: "Run an isolated dry-run later",
        type: "Действие",
        status: "inbox",
        createdAt: "2026-07-25T00:04:00.000Z",
        embeddingModel: "embeddinggemma",
        embedding: [-0.5, 0.75],
        primaryNodeId: "project-1",
        additionalNodeIds: ["direction-1"],
      },
    ],
    links: [{
      id: "legacy-link-1",
      sourceId: "synthetic-001",
      targetId: "synthetic-002",
      type: "Зависит от",
      status: "confirmed",
      createdAt: "2026-07-25T00:06:00.000Z",
      updatedAt: "2026-07-25T00:06:01.000Z",
      legacyMetadata: { reason: "fixture dependency", confidence: 0.9 },
    }],
    runs: [
      {
        runId: "legacy-run-2",
        datasetId: "approved-96-v1",
        orderVariant: "original",
        semanticModel: "qwen3:8b",
        embeddingModel: "embeddinggemma",
        pipelineVersion: "0.6.0-alpha.18",
        sourceBuildId: "legacy-alpha19",
        initialStage: "hierarchy",
        sourceEventCount: 2,
        historyCreatedAt: "2026-07-25T00:08:00.000Z",
        history: { terminal: "failed", eventDigests: ["b", "a"] },
      },
      {
        runId: "legacy-run-1",
        datasetId: "approved-96-v1",
        orderVariant: "round_robin",
        semanticModel: "qwen3:8b",
        embeddingModel: "embeddinggemma",
        pipelineVersion: "0.6.0-alpha.12",
        sourceBuildId: "legacy-alpha19",
        initialStage: "candidates",
        sourceEventCount: 3,
        historyCreatedAt: "2026-07-25T00:07:00.000Z",
        history: { terminal: "paused", eventDigests: ["c", "d", "e"] },
      },
    ],
  };
}
