import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { IDBFactory } from "fake-indexeddb";
import { MINDMAP_GRAPH_NAMESPACE } from "../graph-storage/contracts.ts";
import { InMemoryGraphStorage } from "../graph-storage/in-memory-reference-storage.ts";
import { NativeIndexedDbGraphStorage } from "../graph-storage/indexeddb/native-indexeddb-graph-storage.ts";
import { GRAPH_STORE_NAMES } from "../graph-storage/indexeddb/unified-schema.ts";
import { STATE_STORAGE_NAMESPACE } from "../storage/contracts.ts";
import { NATIVE_STATE_DATABASE_VERSION } from "../storage/indexeddb/native-indexeddb-storage.ts";
const sha256=(v)=>createHash("sha256").update(v).digest("hex");const hashCanonical=(v)=>sha256(v);const hashPayload=(r)=>sha256(r.encoding==="base64"||r.encoding==="float32-le-base64"?Buffer.from(r.data,"base64"):Buffer.from(r.data,"utf8"));let counter=0;const dbName=()=>`${STATE_STORAGE_NAMESPACE}-phase2ca-integrity-${++counter}`;
const payload=(kind,data,workspace="synthetic")=>{const bytes=Buffer.from(data,"utf8");return{namespace:MINDMAP_GRAPH_NAMESPACE,workspace,contentHash:sha256(bytes),kind,mediaType:"text/plain; charset=utf-8",encoding:"utf8",byteLength:bytes.byteLength,data}};const event=(sequence,type,record,eventId)=>({namespace:MINDMAP_GRAPH_NAMESPACE,workspace:record.workspace,sequence,eventId,occurredAt:`2026-07-25T23:00:${String(sequence).padStart(2,"0")}.000Z`,payload:{type,record}});const request=(events,o={})=>({namespace:MINDMAP_GRAPH_NAMESPACE,transactionId:o.transactionId??"tx",idempotencyKey:o.idempotencyKey??"tx:idem",workspace:o.workspace??"synthetic",expectedRevision:o.expectedRevision??0,events});
function linked(){const a=payload("thought-text","A"),b=payload("thought-text","B");const ta={namespace:MINDMAP_GRAPH_NAMESPACE,workspace:"synthetic",thoughtId:"a",revision:1,textPayloadHash:a.contentHash,semanticType:"observation",status:"inbox",createdAt:"2026-07-25T23:01:00.000Z",updatedAt:"2026-07-25T23:01:00.000Z"};const tb={...ta,thoughtId:"b",textPayloadHash:b.contentHash,createdAt:"2026-07-25T23:02:00.000Z",updatedAt:"2026-07-25T23:02:00.000Z"};const pa={namespace:MINDMAP_GRAPH_NAMESPACE,workspace:"synthetic",thoughtId:"a",revision:1,kind:"unresolved",reason:"awaiting_review",updatedAt:"2026-07-25T23:03:00.000Z"};const pb={...pa,thoughtId:"b"};return{ta,tb,events:[event(1,"payload_put",a,"pa"),event(2,"payload_put",b,"pb"),event(3,"thought_put",ta,"ta"),event(4,"placement_put",pa,"pla"),event(5,"thought_put",tb,"tb"),event(6,"placement_put",pb,"plb")]}}
const link=(ta,tb,status="proposed",revision=1)=>({namespace:MINDMAP_GRAPH_NAMESPACE,workspace:"synthetic",linkId:"l",revision,source:{kind:"thought",id:ta.thoughtId},target:{kind:"thought",id:tb.thoughtId},kind:"related",status,createdAt:"2026-07-25T23:04:00.000Z",updatedAt:revision===1?"2026-07-25T23:04:00.000Z":"2026-07-25T23:05:00.000Z"});function minimal(){const p=payload("thought-text","Integrity");const t={namespace:MINDMAP_GRAPH_NAMESPACE,workspace:"synthetic",thoughtId:"corrupt",revision:1,textPayloadHash:p.contentHash,semanticType:"observation",status:"inbox",createdAt:"2026-07-25T23:10:00.000Z",updatedAt:"2026-07-25T23:10:00.000Z"};const pl={namespace:MINDMAP_GRAPH_NAMESPACE,workspace:"synthetic",thoughtId:"corrupt",revision:1,kind:"unresolved",reason:"awaiting_review",updatedAt:"2026-07-25T23:10:00.000Z"};return request([event(1,"payload_put",p,"p"),event(2,"thought_put",t,"t"),event(3,"placement_put",pl,"pl")])}
const openDb=(f,n)=>new Promise((res,rej)=>{const r=f.open(n,NATIVE_STATE_DATABASE_VERSION);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});const done=(tx)=>new Promise((res,rej)=>{tx.oncomplete=()=>res();tx.onabort=()=>rej(tx.error);tx.onerror=()=>{}});const del=(f,n)=>new Promise((res,rej)=>{const r=f.deleteDatabase(n);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);r.onblocked=()=>rej(new Error("blocked"))});
test("link lifecycle",async()=>{const f=linked();const direct=new InMemoryGraphStorage({hashCanonical,hashPayload});const bad=await direct.commit(request([...f.events,event(7,"link_put",link(f.ta,f.tb,"confirmed"),"bad")]));assert.equal(bad.ok,false);assert.equal(bad.rejection.code,"invalid_link");const g=new InMemoryGraphStorage({hashCanonical,hashPayload});assert.equal((await g.commit(request([...f.events,event(7,"link_put",link(f.ta,f.tb),"proposed")]))).ok,true);const confirmed=link(f.ta,f.tb,"confirmed",2);assert.equal((await g.commit(request([event(8,"link_put",confirmed,"confirmed")],{expectedRevision:7,transactionId:"confirm",idempotencyKey:"confirm:idem"}))).ok,true);const down=await g.commit(request([event(9,"link_put",{...confirmed,revision:3,status:"proposed",updatedAt:"2026-07-25T23:06:00.000Z"},"down")],{expectedRevision:8,transactionId:"down",idempotencyKey:"down:idem"}));assert.equal(down.ok,false);assert.equal(down.rejection.code,"invalid_link")});
test("run metadata",async(t)=>{const f=new IDBFactory(),n=dbName();t.after(()=>del(f,n));const g=new NativeIndexedDbGraphStorage({indexedDB:f,databaseName:n,hashCanonical,hashPayload});await g.load("synthetic");g.close();const db=await openDb(f,n),tx=db.transaction(["meta"],"readonly"),r=tx.objectStore("meta").get("schema");const schema=await new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});await done(tx);db.close();assert.equal(schema.namespace,STATE_STORAGE_NAMESPACE);assert.equal(schema.databaseVersion,NATIVE_STATE_DATABASE_VERSION)});
test("corruption detection",async(t)=>{const f=new IDBFactory(),n=dbName();t.after(()=>del(f,n));const first=new NativeIndexedDbGraphStorage({indexedDB:f,databaseName:n,hashCanonical,hashPayload});assert.equal((await first.commit(minimal())).ok,true);first.close();const db=await openDb(f,n),tx=db.transaction([GRAPH_STORE_NAMES.thoughts],"readwrite"),s=tx.objectStore(GRAPH_STORE_NAMES.thoughts),r=s.get(["synthetic","corrupt"]);const thought=await new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});s.put({...thought,status:"archived"});await done(tx);db.close();const reopened=new NativeIndexedDbGraphStorage({indexedDB:f,databaseName:n,hashCanonical,hashPayload});await assert.rejects(reopened.load("synthetic"),/graph_state_replay_mismatch|graph_state_hash_mismatch/);const blocked=await reopened.commit(request([event(4,"payload_put",payload("artifact-json","{}"),"extra")],{expectedRevision:3,transactionId:"follow",idempotencyKey:"follow:idem"}));assert.equal(blocked.ok,false);assert.equal(blocked.rejection.code,"integrity_mismatch");reopened.close()});
